const SET_CALCULATOR_ERROR = 'SET_CALCULATOR_ERROR';

const SET_NUMBER_OF_SAMPLES = 'SET_NUMBER_OF_SAMPLES';
const SET_PROPORTIONS_OR_MEANS = 'SET_PROPORTIONS_OR_MEANS';

const SET_SAMPLE_DATA = 'SET_SAMPLE_DATA';

const SET_OPTIONS = 'SET_OPTIONS';

const SET_STEP_COMPLETED = 'SET_STEP_COMPLETED';

export {
  SET_NUMBER_OF_SAMPLES,
  SET_PROPORTIONS_OR_MEANS,
  SET_SAMPLE_DATA,
  SET_CALCULATOR_ERROR,
  SET_OPTIONS,
  SET_STEP_COMPLETED
};
